config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :strains
  resources :wines
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "wines#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/magazine.rb
class Magazine < ApplicationRecord
    has_and_belongs_to_many :oenologist
end

app/models/oenologist.rb
class Oenologist < ApplicationRecord
    has_and_belongs_to_many :magazine
end

app/models/strain.rb
class Strain < ApplicationRecord
    has_many :wine_strains
    has_many :wines, through: :wine_strains
    validates :name, presence: true
    validates :name, uniqueness: { case_sensitive: false } 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains
    has_many :strains, through: :wine_strains
    accepts_nested_attributes_for :wine_strains, allow_destroy: true 

end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
  accepts_nested_attributes_for :strain 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authorize_editor!
        unless current_user.editor?
            flash[alert]= 'You must be an editor to acces this section'
            redirect_to root_path
        end
    end
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: %i[ show edit update destroy ]

  # GET /strains or /strains.json
  def index
    @strains = Strain.all
  end

  # GET /strains/1 or /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains or /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to @strain, notice: "Strain was successfully created." }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1 or /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to @strain, notice: "Strain was successfully updated." }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1 or /strains/1.json
  def destroy
    @strain.destroy
    respond_to do |format|
      format.html { redirect_to strains_url, notice: "Strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wine, only: %i[ show edit update destroy ]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @wine.wine_strains.build
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :score, wine_strains_attributes: [:percentage, :_destroy, :id, :strain_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wines_helper.rb
module WinesHelper
    def strains_for_select
        Strain.order(:name).collect { |g| [g.name, g.id] }
    end 
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <title>Wineapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'wines/header' %>
    <div class="container">
    </br>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    </br>        
    <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/strains/_form.html.erb
<%= form_with(model: strain, local: true) do |form| %>
  <% if strain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(strain.errors.count, "error") %> prohibited this strain from being saved:</h2>

      <ul>
      <% strain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/strains/edit.html.erb
<h1>Editing Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Show', @strain %> |
<%= link_to 'Back', strains_path %>

app/views/strains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Strains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strains.each do |strain| %>
      <tr>
        <td><%= strain.name %></td>
        <td><%= link_to 'Show', strain %></td>
        <td><%= link_to 'Edit', edit_strain_path(strain) %></td>
        <td><%= link_to 'Destroy', strain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strain', new_strain_path %>

app/views/strains/new.html.erb
<h1>New Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Back', strains_path %>

app/views/strains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @strain.name %>
</p>

<%= link_to 'Edit', edit_strain_path(@strain) %> |
<%= link_to 'Back', strains_path %>

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
  <%= form.label :score %>
  <%= form.text_field :score %>
</div>

  <div id="wine_strains" class="form-group">
    <%= form.fields_for :wine_strains do |strain_wine_form| %>
      <%= render 'wine_strain_fields', f: strain_wine_form %>
    <% end %>
    <div class="links form-inline">
      <%= link_to_add_association 'add strain', form, :wine_strains %>
    </div>
  </div> 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_header.html.erb
<nav class="navbar navbar-light" style="background-color: #4000FF">
  <%= link_to 'Wine App', root_path, class:"navbar-brand" %>  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link" %> 
        </li>
        <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class:"nav-link" %> 
        </li>
      <% else %>
        <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %> 
        </li>
        <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, class:"nav-link" %> 
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/wines/_wine_strain_fields.html.erb
<div class="nested-fields form-inline">
    <%= f.select :strain_id, strains_for_select, {}, class: 'custom-select mx-sm-3 mb-2' %>
    <div class="form-group mr-sm-3 mb-2">
        <%= f.text_field :percentage, class: 'form-control mr-sm-3' %>
        <%= f.label :percentage, '%' %>
    </div>
</div> 

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Strains</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
        <tr>
          <td><%= wine.name %></td>
          <td><% wine.wine_strains.each do |wine_strain| %>
                <li><%= wine_strain.strain.name %> <%= "(#{wine_strain.percentage} %)"%></li>
              <% end %>        
          </td>
          <td><%= wine.score %></td>
            <td><%= link_to 'Show', wine %></td>
            <% if current_user.editor? %>
              <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
              <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.editor? %>
<%= link_to 'New Wine', new_wine_path %>
<% end %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>